/**
 * System-wide medication dictionary — clinician-authored, available to every clinician automatically.
 * Derived from the clinic's curated starter CSV. Clinicians can add custom aliases on top
 * via the inline "Verify" action in the encounter transcript panel.
 */

export type SeedEntry = {
  genericName: string;
  brandNames: string[];
  commonSpokenVariants: string[];
  commonMisspellings: string[];
  drugClass: string;
  subclass?: string;
  route?: string;
  notes?: string;
};

export const SYSTEM_MEDICATIONS: SeedEntry[] = [

  // ─── Hormones ────────────────────────────────────────────────────────────────
  {
    genericName: "estradiol",
    brandNames: ["Estrace", "Vivelle-Dot", "Climara", "Dotti", "Minivelle", "Alora", "Elestrin", "Divigel", "EstroGel"],
    commonSpokenVariants: ["estradiol", "estrace", "vivelle", "vivelle dot", "climara", "dotti", "minivelle", "alora", "elestrin", "divigel", "estrogel", "estrogen patch", "estradiol patch", "estradiol cream", "estradiol gel"],
    commonMisspellings: ["estridol", "estradial", "estradoil", "vivel dot"],
    drugClass: "Estrogen",
    subclass: "Menopausal hormone therapy",
    route: "transdermal|oral|vaginal|topical",
    notes: "Normalize to estradiol; preserve formulation if known",
  },
  {
    genericName: "progesterone",
    brandNames: ["Prometrium"],
    commonSpokenVariants: ["progesterone", "prometrium", "micronized progesterone"],
    commonMisspellings: ["progesteron", "prometriume"],
    drugClass: "Progestogen",
    subclass: "Menopausal hormone therapy",
    route: "oral",
    notes: "Distinguish from medroxyprogesterone",
  },
  {
    genericName: "medroxyprogesterone",
    brandNames: ["Provera", "Depo-Provera"],
    commonSpokenVariants: ["medroxyprogesterone", "provera", "depo provera", "depo"],
    commonMisspellings: ["medroxyprogestrone", "provra"],
    drugClass: "Progestin",
    subclass: "Synthetic progestin",
    route: "oral|intramuscular",
    notes: "Do not normalize to micronized progesterone",
  },
  {
    genericName: "testosterone",
    brandNames: ["AndroGel", "Testim", "Axiron", "Fortesta", "Androderm"],
    commonSpokenVariants: ["testosterone", "androgel", "testim", "axiron", "fortesta", "testosterone gel", "testosterone cream", "T shot", "T injection", "hormone injection", "TRT", "testosterone therapy", "weekly shot"],
    commonMisspellings: ["testosteron", "testoterone", "testostrone"],
    drugClass: "Androgen",
    subclass: "Testosterone therapy",
    route: "topical|transdermal|intramuscular|subcutaneous",
    notes: "Preserve route if known",
  },
  {
    genericName: "testosterone cypionate",
    brandNames: ["Depo-Testosterone"],
    commonSpokenVariants: ["testosterone cypionate", "test cyp", "depo testosterone", "cyp", "cypionate"],
    commonMisspellings: ["testosterone cypiontate", "test cypionate"],
    drugClass: "Androgen",
    subclass: "Injectable testosterone",
    route: "intramuscular|subcutaneous",
    notes: "Normalize injectable shorthand to testosterone cypionate when clearly stated",
  },
  {
    genericName: "testosterone enanthate",
    brandNames: ["Xyosted", "Delatestryl"],
    commonSpokenVariants: ["testosterone enanthate", "xyosted", "delatestryl", "test e"],
    commonMisspellings: ["testosterone enanthat", "delatrysl"],
    drugClass: "Androgen",
    subclass: "Injectable testosterone",
    route: "subcutaneous|intramuscular",
  },
  {
    genericName: "prasterone",
    brandNames: ["Intrarosa"],
    commonSpokenVariants: ["prasterone", "intrarosa", "vaginal dhea"],
    commonMisspellings: ["prasteron", "introrosa"],
    drugClass: "Hormone",
    subclass: "Vaginal DHEA",
    route: "vaginal",
    notes: "Keep separate from oral DHEA",
  },
  {
    genericName: "dehydroepiandrosterone",
    brandNames: ["DHEA"],
    commonSpokenVariants: ["dhea", "dehydroepiandrosterone", "DHEA supplement", "adrenal hormone"],
    commonMisspellings: ["dehydroepiandosterone", "dhes", "DHAE"],
    drugClass: "Hormone precursor",
    subclass: "Adrenal androgen precursor",
    route: "oral",
    notes: "Supplement/common shorthand likely used",
  },
  {
    genericName: "pregnenolone",
    brandNames: [],
    commonSpokenVariants: ["pregnenolone", "preg", "master hormone", "neurosteroid"],
    commonMisspellings: ["pregnenelone", "pregnalonone", "pregneolone"],
    drugClass: "Hormone precursor",
    subclass: "Neurosteroid precursor",
    route: "oral",
  },
  {
    genericName: "spironolactone",
    brandNames: ["Aldactone", "CaroSpir"],
    commonSpokenVariants: ["spironolactone", "aldactone", "spirono", "spiro", "water pill", "anti-androgen", "acne pill"],
    commonMisspellings: ["spironolacone", "spironlactone", "spironaolactone"],
    drugClass: "Diuretic",
    subclass: "Potassium-sparing diuretic/antiandrogen",
    route: "oral",
    notes: "Often used for acne/hirsutism",
  },
  {
    genericName: "finasteride",
    brandNames: ["Propecia", "Proscar"],
    commonSpokenVariants: ["finasteride", "propecia", "proscar", "hair loss medication", "DHT blocker"],
    commonMisspellings: ["finasteridee", "propeci", "finasterid"],
    drugClass: "5-alpha reductase inhibitor",
    subclass: "Antiandrogen",
    route: "oral",
  },
  {
    genericName: "dutasteride",
    brandNames: ["Avodart"],
    commonSpokenVariants: ["dutasteride", "avodart", "DHT blocker", "hair loss medication"],
    commonMisspellings: ["dutasturide", "avodrt", "dutasterid"],
    drugClass: "5-alpha reductase inhibitor",
    subclass: "Antiandrogen",
    route: "oral",
  },
  {
    genericName: "clobetasol",
    brandNames: ["Temovate", "Clobex"],
    commonSpokenVariants: ["clobetasol", "temovate", "clobex", "steroid cream"],
    commonMisspellings: ["clobetasole", "clobetsol"],
    drugClass: "Topical corticosteroid",
    subclass: "High-potency steroid",
    route: "topical",
    notes: "Useful for lichen sclerosus recognition",
  },
  {
    genericName: "estradiol-norethindrone",
    brandNames: ["CombiPatch", "Activella", "Mimvey"],
    commonSpokenVariants: ["combipatch", "activella", "mimvey", "estradiol norethindrone", "combination patch"],
    commonMisspellings: ["combipach", "actvella"],
    drugClass: "Hormone combination",
    subclass: "Estrogen/progestin therapy",
    route: "transdermal|oral",
    notes: "Combination product",
  },

  // ─── Thyroid ─────────────────────────────────────────────────────────────────
  {
    genericName: "levothyroxine",
    brandNames: ["Synthroid", "Levoxyl", "Unithroid", "Tirosint", "Euthyrox"],
    commonSpokenVariants: ["levothyroxine", "synthroid", "levoxyl", "unithroid", "tirosint", "euthyrox", "thyroid pill", "thyroid medication", "thyroid hormone", "T4", "thyroid replacement"],
    commonMisspellings: ["levothryoxine", "levothyroxin", "synthriod", "levothyroxne"],
    drugClass: "Thyroid hormone",
    subclass: "T4 replacement",
    route: "oral",
  },
  {
    genericName: "liothyronine",
    brandNames: ["Cytomel", "Triostat"],
    commonSpokenVariants: ["liothyronine", "cytomel", "t3", "T3 pill", "active thyroid hormone"],
    commonMisspellings: ["liothryonine", "liothyroinine", "cytomell"],
    drugClass: "Thyroid hormone",
    subclass: "T3 replacement",
    route: "oral|intravenous",
  },
  {
    genericName: "desiccated thyroid",
    brandNames: ["Armour Thyroid", "NP Thyroid", "Nature-Throid", "WP Thyroid"],
    commonSpokenVariants: ["armour thyroid", "armour", "np thyroid", "nature throid", "wp thyroid", "desiccated thyroid", "natural thyroid", "NDT", "pig thyroid"],
    commonMisspellings: ["armor thyroid", "armour thryoid", "np thryoid", "dessicated thyroid"],
    drugClass: "Thyroid hormone",
    subclass: "Natural desiccated thyroid",
    route: "oral",
  },
  {
    genericName: "methimazole",
    brandNames: ["Tapazole"],
    commonSpokenVariants: ["methimazole", "tapazole", "anti-thyroid medication", "thyroid blocker"],
    commonMisspellings: ["methimazol", "tapazol"],
    drugClass: "Antithyroid",
    subclass: "Thionamide",
    route: "oral",
  },
  {
    genericName: "propylthiouracil",
    brandNames: ["PTU"],
    commonSpokenVariants: ["propylthiouracil", "ptu", "PTU"],
    commonMisspellings: ["propylthyouracil", "propythiouracil"],
    drugClass: "Antithyroid",
    subclass: "Thionamide",
    route: "oral",
  },

  // ─── GLP-1 / Weight Management ───────────────────────────────────────────────
  {
    genericName: "semaglutide",
    brandNames: ["Ozempic", "Wegovy", "Rybelsus"],
    commonSpokenVariants: ["semaglutide", "ozempic", "wegovy", "rybelsus", "GLP shot", "weekly shot", "weight loss shot", "sema"],
    commonMisspellings: ["semaglutde", "ozembic", "wegovyy", "semalgutide"],
    drugClass: "GLP-1 receptor agonist",
    subclass: "Incretin mimetic",
    route: "subcutaneous|oral",
    notes: "Normalize brands to semaglutide",
  },
  {
    genericName: "tirzepatide",
    brandNames: ["Mounjaro", "Zepbound"],
    commonSpokenVariants: ["tirzepatide", "mounjaro", "zepbound", "tirza", "dual agonist", "GIP GLP shot"],
    commonMisspellings: ["tirzepatde", "monjaro", "zepboound", "tirzepeptide", "tersapeptide"],
    drugClass: "GIP/GLP-1 receptor agonist",
    subclass: "Dual incretin agonist",
    route: "subcutaneous",
    notes: "Normalize brands to tirzepatide",
  },
  {
    genericName: "metformin",
    brandNames: ["Glucophage", "Glucophage XR", "Fortamet", "Riomet"],
    commonSpokenVariants: ["metformin", "glucophage", "glucophage xr", "fortamet", "riomet", "metformin xr", "diabetes pill", "sugar pill"],
    commonMisspellings: ["metforman", "metfornin", "glucaphage", "metphormin"],
    drugClass: "Antidiabetic",
    subclass: "Biguanide",
    route: "oral",
    notes: "Normalize XR/ER variants to metformin unless formulation tracking needed",
  },
  {
    genericName: "empagliflozin",
    brandNames: ["Jardiance"],
    commonSpokenVariants: ["empagliflozin", "jardiance", "SGLT2 inhibitor"],
    commonMisspellings: ["empaglaflozin"],
    drugClass: "Antidiabetic",
    subclass: "SGLT2 inhibitor",
    route: "oral",
  },
  {
    genericName: "dapagliflozin",
    brandNames: ["Farxiga"],
    commonSpokenVariants: ["dapagliflozin", "farxiga"],
    commonMisspellings: ["dapagliflozen", "farziga"],
    drugClass: "Antidiabetic",
    subclass: "SGLT2 inhibitor",
    route: "oral",
  },
  {
    genericName: "canagliflozin",
    brandNames: ["Invokana"],
    commonSpokenVariants: ["canagliflozin", "invokana"],
    commonMisspellings: ["canagliflozen", "invokanna"],
    drugClass: "Antidiabetic",
    subclass: "SGLT2 inhibitor",
    route: "oral",
  },
  {
    genericName: "glimepiride",
    brandNames: ["Amaryl"],
    commonSpokenVariants: ["glimepiride", "amaryl"],
    commonMisspellings: ["glimiperide", "amaril"],
    drugClass: "Antidiabetic",
    subclass: "Sulfonylurea",
    route: "oral",
  },
  {
    genericName: "glipizide",
    brandNames: ["Glucotrol", "Glucotrol XL"],
    commonSpokenVariants: ["glipizide", "glucotrol", "glucotrol xl"],
    commonMisspellings: ["glipizid", "glucatrol"],
    drugClass: "Antidiabetic",
    subclass: "Sulfonylurea",
    route: "oral",
  },
  {
    genericName: "insulin glargine",
    brandNames: ["Lantus", "Basaglar", "Toujeo", "Semglee"],
    commonSpokenVariants: ["insulin glargine", "lantus", "basaglar", "toujeo", "semglee", "long-acting insulin", "basal insulin"],
    commonMisspellings: ["insulin glargene", "basagler"],
    drugClass: "Antidiabetic",
    subclass: "Long-acting insulin",
    route: "subcutaneous",
  },
  {
    genericName: "insulin lispro",
    brandNames: ["Humalog", "Admelog", "Lyumjev"],
    commonSpokenVariants: ["insulin lispro", "humalog", "admelog", "lyumjev", "rapid insulin", "fast-acting insulin"],
    commonMisspellings: ["lisproe", "humolog"],
    drugClass: "Antidiabetic",
    subclass: "Rapid-acting insulin",
    route: "subcutaneous",
  },
  {
    genericName: "phentermine",
    brandNames: ["Adipex-P", "Lomaira"],
    commonSpokenVariants: ["phentermine", "adipex", "adipex p", "lomaira", "diet pill", "appetite pill", "weight pill"],
    commonMisspellings: ["phentarmine", "phentremine", "phentamine"],
    drugClass: "Anorexiant",
    subclass: "Sympathomimetic",
    route: "oral",
    notes: "Weight-management med frequently mentioned",
  },
  {
    genericName: "naltrexone-bupropion",
    brandNames: ["Contrave"],
    commonSpokenVariants: ["contrave", "naltrexone bupropion", "weight loss combination"],
    commonMisspellings: ["contrav", "naltrexon bupropion"],
    drugClass: "Weight management",
    subclass: "Combination therapy",
    route: "oral",
    notes: "Combination product",
  },

  // ─── Lipids ──────────────────────────────────────────────────────────────────
  {
    genericName: "rosuvastatin",
    brandNames: ["Crestor", "Ezallor"],
    commonSpokenVariants: ["rosuvastatin", "crestor", "rosuva", "statin", "cholesterol pill"],
    commonMisspellings: ["rosuvastin", "rosuvastatan", "crestorr"],
    drugClass: "Antilipemic",
    subclass: "Statin",
    route: "oral",
  },
  {
    genericName: "atorvastatin",
    brandNames: ["Lipitor"],
    commonSpokenVariants: ["atorvastatin", "lipitor", "statin", "cholesterol medication"],
    commonMisspellings: ["atorvostatin", "liptor", "atoravastin"],
    drugClass: "Antilipemic",
    subclass: "Statin",
    route: "oral",
  },
  {
    genericName: "pravastatin",
    brandNames: ["Pravachol"],
    commonSpokenVariants: ["pravastatin", "pravachol"],
    commonMisspellings: ["pravastin", "pravacol"],
    drugClass: "Antilipemic",
    subclass: "Statin",
    route: "oral",
  },
  {
    genericName: "simvastatin",
    brandNames: ["Zocor"],
    commonSpokenVariants: ["simvastatin", "zocor"],
    commonMisspellings: ["simvastin", "zocar"],
    drugClass: "Antilipemic",
    subclass: "Statin",
    route: "oral",
  },
  {
    genericName: "ezetimibe",
    brandNames: ["Zetia"],
    commonSpokenVariants: ["ezetimibe", "zetia", "cholesterol absorption inhibitor"],
    commonMisspellings: ["ezitimibe", "zetta"],
    drugClass: "Antilipemic",
    subclass: "Cholesterol absorption inhibitor",
    route: "oral",
  },
  {
    genericName: "bempedoic acid",
    brandNames: ["Nexletol"],
    commonSpokenVariants: ["bempedoic acid", "nexletol"],
    commonMisspellings: ["bempedoik acid", "nexlatol"],
    drugClass: "Antilipemic",
    subclass: "ACL inhibitor",
    route: "oral",
  },
  {
    genericName: "icosapent ethyl",
    brandNames: ["Vascepa"],
    commonSpokenVariants: ["icosapent ethyl", "vascepa", "fish oil prescription", "omega-3 prescription"],
    commonMisspellings: ["icosapent ethel", "vascpa"],
    drugClass: "Antilipemic",
    subclass: "Omega-3 derivative",
    route: "oral",
  },

  // ─── Cardiovascular / Antihypertensive ───────────────────────────────────────
  {
    genericName: "lisinopril",
    brandNames: ["Prinivil", "Zestril", "Qbrelis"],
    commonSpokenVariants: ["lisinopril", "prinivil", "zestril", "ACE inhibitor", "blood pressure pill", "liza nopril", "lisa nopril", "liz nopril"],
    commonMisspellings: ["lisonopril", "lisinpril", "lisenopril"],
    drugClass: "Antihypertensive",
    subclass: "ACE inhibitor",
    route: "oral",
  },
  {
    genericName: "losartan",
    brandNames: ["Cozaar"],
    commonSpokenVariants: ["losartan", "cozaar", "ARB", "blood pressure medication", "liz sartan", "liz artan", "liz arton", "Liz Sartan"],
    commonMisspellings: ["losartanr", "cozarr", "lozartan", "losarton"],
    drugClass: "Antihypertensive",
    subclass: "ARB",
    route: "oral",
  },
  {
    genericName: "valsartan",
    brandNames: ["Diovan"],
    commonSpokenVariants: ["valsartan", "diovan", "ARB"],
    commonMisspellings: ["valsartin", "divan"],
    drugClass: "Antihypertensive",
    subclass: "ARB",
    route: "oral",
  },
  {
    genericName: "amlodipine",
    brandNames: ["Norvasc", "Katerzia"],
    commonSpokenVariants: ["amlodipine", "norvasc", "calcium channel blocker", "am lo dip een", "am lo dip in"],
    commonMisspellings: ["amlodipin", "norvask", "amlodopine"],
    drugClass: "Antihypertensive",
    subclass: "Calcium channel blocker",
    route: "oral",
  },
  {
    genericName: "hydrochlorothiazide",
    brandNames: ["Microzide"],
    commonSpokenVariants: ["hydrochlorothiazide", "hctz", "microzide", "hydrodiuril", "HCTZ", "water pill", "thiazide"],
    commonMisspellings: ["hydrochlorathiazide", "hydrochlorthiazide"],
    drugClass: "Antihypertensive",
    subclass: "Thiazide diuretic",
    route: "oral",
    notes: "Common shorthand HCTZ",
  },
  {
    genericName: "chlorthalidone",
    brandNames: ["Thalitone", "Hygroton"],
    commonSpokenVariants: ["chlorthalidone", "thalitone", "hygroton"],
    commonMisspellings: ["chlorthalidon"],
    drugClass: "Antihypertensive",
    subclass: "Thiazide-like diuretic",
    route: "oral",
  },
  {
    genericName: "metoprolol succinate",
    brandNames: ["Toprol-XL"],
    commonSpokenVariants: ["metoprolol succinate", "toprol xl", "toprol", "beta blocker", "heart rate pill"],
    commonMisspellings: ["metoprolol sucinate", "metroprolol", "toporol"],
    drugClass: "Antihypertensive",
    subclass: "Beta blocker",
    route: "oral",
    notes: "If spoken as Toprol, likely succinate",
  },
  {
    genericName: "metoprolol tartrate",
    brandNames: ["Lopressor"],
    commonSpokenVariants: ["metoprolol tartrate", "lopressor"],
    commonMisspellings: ["metoprolol tatrate", "lopresor"],
    drugClass: "Antihypertensive",
    subclass: "Beta blocker",
    route: "oral",
    notes: "Keep separate from succinate if identifiable",
  },
  {
    genericName: "propranolol",
    brandNames: ["Inderal", "InnoPran XL"],
    commonSpokenVariants: ["propranolol", "inderal", "beta blocker"],
    commonMisspellings: ["propanolol", "inderol"],
    drugClass: "Antihypertensive",
    subclass: "Beta blocker",
    route: "oral",
  },
  {
    genericName: "nebivolol",
    brandNames: ["Bystolic"],
    commonSpokenVariants: ["nebivolol", "bystolic"],
    commonMisspellings: ["nebivol", "bystollic"],
    drugClass: "Antihypertensive",
    subclass: "Beta blocker",
    route: "oral",
  },
  {
    genericName: "furosemide",
    brandNames: ["Lasix"],
    commonSpokenVariants: ["furosemide", "lasix", "water pill", "fluid pill", "diuretic", "pee pill", "swelling pill"],
    commonMisspellings: ["furosimide", "lasics", "furesemide"],
    drugClass: "Diuretic",
    subclass: "Loop diuretic",
    route: "oral|intravenous",
  },

  // ─── Psychiatry / Neurology ───────────────────────────────────────────────────
  {
    genericName: "bupropion",
    brandNames: ["Wellbutrin", "Wellbutrin XL", "Wellbutrin SR", "Aplenzin"],
    commonSpokenVariants: ["bupropion", "wellbutrin", "wellbutrin xl", "wellbutrin sr", "NDRI", "antidepressant", "smoking cessation"],
    commonMisspellings: ["bupriopion", "buproprion", "welbutrin"],
    drugClass: "Antidepressant",
    subclass: "NDRI",
    route: "oral",
  },
  {
    genericName: "sertraline",
    brandNames: ["Zoloft"],
    commonSpokenVariants: ["sertraline", "zoloft", "SSRI", "antidepressant"],
    commonMisspellings: ["sertralin", "zolof", "sertaline"],
    drugClass: "Antidepressant",
    subclass: "SSRI",
    route: "oral",
  },
  {
    genericName: "escitalopram",
    brandNames: ["Lexapro"],
    commonSpokenVariants: ["escitalopram", "lexapro", "SSRI", "anxiety pill"],
    commonMisspellings: ["escitalpram", "lexaproo", "escitalopran"],
    drugClass: "Antidepressant",
    subclass: "SSRI",
    route: "oral",
  },
  {
    genericName: "fluoxetine",
    brandNames: ["Prozac", "Sarafem"],
    commonSpokenVariants: ["fluoxetine", "prozac", "sarafem", "SSRI"],
    commonMisspellings: ["fluoxitine", "prozak"],
    drugClass: "Antidepressant",
    subclass: "SSRI",
    route: "oral",
  },
  {
    genericName: "venlafaxine",
    brandNames: ["Effexor XR", "Effexor"],
    commonSpokenVariants: ["venlafaxine", "effexor", "effexor xr", "SNRI", "antidepressant"],
    commonMisspellings: ["venlafaxin", "efexor", "venflafaxine"],
    drugClass: "Antidepressant",
    subclass: "SNRI",
    route: "oral",
  },
  {
    genericName: "duloxetine",
    brandNames: ["Cymbalta", "Drizalma"],
    commonSpokenVariants: ["duloxetine", "cymbalta", "SNRI", "nerve pain medication"],
    commonMisspellings: ["duloxitine", "cymbolta"],
    drugClass: "Antidepressant",
    subclass: "SNRI",
    route: "oral",
  },
  {
    genericName: "trazodone",
    brandNames: ["Desyrel"],
    commonSpokenVariants: ["trazodone", "sleep medication", "sleep aid"],
    commonMisspellings: ["trazadone", "trazdone"],
    drugClass: "Antidepressant",
    subclass: "Serotonin modulator",
    route: "oral",
    notes: "Often used for sleep",
  },
  {
    genericName: "hydroxyzine",
    brandNames: ["Atarax", "Vistaril"],
    commonSpokenVariants: ["hydroxyzine", "atarax", "vistaril", "anxiety medication"],
    commonMisspellings: ["hydroxyzin", "vistaral"],
    drugClass: "Antihistamine",
    subclass: "Anxiolytic/antihistamine",
    route: "oral",
  },
  {
    genericName: "alprazolam",
    brandNames: ["Xanax", "Xanax XR"],
    commonSpokenVariants: ["alprazolam", "xanax", "benzo", "anxiety medication", "panic attack medication"],
    commonMisspellings: ["alprozolam", "zanax"],
    drugClass: "Anxiolytic",
    subclass: "Benzodiazepine",
    route: "oral",
    notes: "Controlled substance",
  },
  {
    genericName: "clonazepam",
    brandNames: ["Klonopin"],
    commonSpokenVariants: ["clonazepam", "klonopin", "benzo"],
    commonMisspellings: ["clonazpam", "clonapin"],
    drugClass: "Anxiolytic",
    subclass: "Benzodiazepine",
    route: "oral",
    notes: "Controlled substance",
  },
  {
    genericName: "lorazepam",
    brandNames: ["Ativan"],
    commonSpokenVariants: ["lorazepam", "ativan", "benzo"],
    commonMisspellings: ["lorazapam", "ativin"],
    drugClass: "Anxiolytic",
    subclass: "Benzodiazepine",
    route: "oral",
    notes: "Controlled substance",
  },
  {
    genericName: "amphetamine-dextroamphetamine",
    brandNames: ["Adderall", "Adderall XR"],
    commonSpokenVariants: ["adderall", "adderall xr", "amphetamine dextroamphetamine", "ADHD medication", "stimulant"],
    commonMisspellings: ["aderall", "amfetamine dextroamphetamine"],
    drugClass: "CNS stimulant",
    subclass: "ADHD stimulant",
    route: "oral",
    notes: "Controlled substance",
  },
  {
    genericName: "lisdexamfetamine",
    brandNames: ["Vyvanse"],
    commonSpokenVariants: ["lisdexamfetamine", "vyvanse", "ADHD medication"],
    commonMisspellings: ["lisdexamphetamine", "vyvance"],
    drugClass: "CNS stimulant",
    subclass: "ADHD stimulant",
    route: "oral",
    notes: "Controlled substance",
  },
  {
    genericName: "zolpidem",
    brandNames: ["Ambien", "Ambien CR"],
    commonSpokenVariants: ["zolpidem", "ambien", "sleep medication", "sleeping pill"],
    commonMisspellings: ["zolpidemm", "ambein"],
    drugClass: "Sedative-hypnotic",
    subclass: "Z-drug",
    route: "oral",
    notes: "Controlled substance",
  },

  // ─── Respiratory ─────────────────────────────────────────────────────────────
  {
    genericName: "albuterol",
    brandNames: ["ProAir HFA", "Ventolin HFA", "Proventil HFA", "AccuNeb"],
    commonSpokenVariants: ["albuterol", "proair", "ventolin", "proventil", "albuterol inhaler", "rescue inhaler", "blue inhaler", "puffer", "quick relief inhaler"],
    commonMisspellings: ["albuteral", "albutarol", "ventilin"],
    drugClass: "Bronchodilator",
    subclass: "Short-acting beta agonist",
    route: "inhalation|nebulized",
    notes: "Preserve HFA/nebulizer if known",
  },
  {
    genericName: "budesonide-formoterol",
    brandNames: ["Symbicort", "Breyna"],
    commonSpokenVariants: ["symbicort", "breyna", "budesonide formoterol", "combination inhaler"],
    commonMisspellings: ["simbicort", "budesonide formoterall"],
    drugClass: "Respiratory",
    subclass: "ICS/LABA",
    route: "inhalation",
    notes: "Combination inhaler",
  },
  {
    genericName: "fluticasone-salmeterol",
    brandNames: ["Advair Diskus", "Advair HFA", "Wixela Inhub"],
    commonSpokenVariants: ["advair", "wixela", "fluticasone salmeterol", "combination inhaler"],
    commonMisspellings: ["fluticasone salmeteral"],
    drugClass: "Respiratory",
    subclass: "ICS/LABA",
    route: "inhalation",
    notes: "Combination inhaler",
  },
  {
    genericName: "fluticasone-vilanterol",
    brandNames: ["Breo Ellipta"],
    commonSpokenVariants: ["breo", "breo ellipta", "fluticasone vilanterol"],
    commonMisspellings: ["breoo", "vilanteral"],
    drugClass: "Respiratory",
    subclass: "ICS/LABA",
    route: "inhalation",
  },
  {
    genericName: "montelukast",
    brandNames: ["Singulair"],
    commonSpokenVariants: ["montelukast", "singulair", "allergy tablet", "leukotriene modifier"],
    commonMisspellings: ["montelukest", "singulaire"],
    drugClass: "Respiratory",
    subclass: "Leukotriene receptor antagonist",
    route: "oral",
  },
  {
    genericName: "fluticasone nasal",
    brandNames: ["Flonase", "Xhance"],
    commonSpokenVariants: ["fluticasone", "flonase", "xhance", "fluticasone nasal", "nasal spray", "allergy spray", "nose spray"],
    commonMisspellings: ["fluticazone", "flonaze"],
    drugClass: "Intranasal steroid",
    subclass: "Corticosteroid",
    route: "nasal",
  },

  // ─── Antihistamines ──────────────────────────────────────────────────────────
  {
    genericName: "cetirizine",
    brandNames: ["Zyrtec"],
    commonSpokenVariants: ["cetirizine", "zyrtec", "allergy pill"],
    commonMisspellings: ["cetrizine", "zirtec"],
    drugClass: "Antihistamine",
    subclass: "Second-generation antihistamine",
    route: "oral",
  },
  {
    genericName: "levocetirizine",
    brandNames: ["Xyzal"],
    commonSpokenVariants: ["levocetirizine", "xyzal"],
    commonMisspellings: ["levocetrizine", "xysal"],
    drugClass: "Antihistamine",
    subclass: "Second-generation antihistamine",
    route: "oral",
  },
  {
    genericName: "fexofenadine",
    brandNames: ["Allegra"],
    commonSpokenVariants: ["fexofenadine", "allegra"],
    commonMisspellings: ["alegra"],
    drugClass: "Antihistamine",
    subclass: "Second-generation antihistamine",
    route: "oral",
  },
  {
    genericName: "loratadine",
    brandNames: ["Claritin"],
    commonSpokenVariants: ["loratadine", "claritin", "allergy pill"],
    commonMisspellings: ["loratidine", "clariten"],
    drugClass: "Antihistamine",
    subclass: "Second-generation antihistamine",
    route: "oral",
  },

  // ─── GI ──────────────────────────────────────────────────────────────────────
  {
    genericName: "omeprazole",
    brandNames: ["Prilosec"],
    commonSpokenVariants: ["omeprazole", "prilosec", "acid pill", "stomach pill", "reflux medication", "heartburn pill", "PPI"],
    commonMisspellings: ["omeprazol", "prilosek"],
    drugClass: "Gastrointestinal",
    subclass: "Proton pump inhibitor",
    route: "oral",
  },
  {
    genericName: "pantoprazole",
    brandNames: ["Protonix"],
    commonSpokenVariants: ["pantoprazole", "protonix", "acid reflux pill", "PPI"],
    commonMisspellings: ["pantaprazole", "protonics"],
    drugClass: "Gastrointestinal",
    subclass: "Proton pump inhibitor",
    route: "oral",
  },
  {
    genericName: "famotidine",
    brandNames: ["Pepcid"],
    commonSpokenVariants: ["famotidine", "pepcid", "H2 blocker", "heartburn medication"],
    commonMisspellings: ["famotidinee", "pepsid"],
    drugClass: "Gastrointestinal",
    subclass: "H2 blocker",
    route: "oral|intravenous",
  },
  {
    genericName: "ondansetron",
    brandNames: ["Zofran"],
    commonSpokenVariants: ["ondansetron", "zofran", "nausea medication", "anti-nausea tablet"],
    commonMisspellings: ["ondansetron", "zofrann"],
    drugClass: "Antiemetic",
    subclass: "5-HT3 antagonist",
    route: "oral|intravenous|ODT",
  },

  // ─── Antibiotics / Antivirals / Antifungals ───────────────────────────────────
  {
    genericName: "amoxicillin",
    brandNames: ["Amoxil"],
    commonSpokenVariants: ["amoxicillin", "amoxil", "antibiotic"],
    commonMisspellings: ["amoxacillin", "amoxicillan"],
    drugClass: "Antibiotic",
    subclass: "Penicillin",
    route: "oral",
  },
  {
    genericName: "amoxicillin-clavulanate",
    brandNames: ["Augmentin"],
    commonSpokenVariants: ["augmentin", "amoxicillin clavulanate", "amox clav"],
    commonMisspellings: ["amox clavulanate", "augmenten"],
    drugClass: "Antibiotic",
    subclass: "Penicillin/beta-lactamase inhibitor",
    route: "oral",
    notes: "Combination product",
  },
  {
    genericName: "azithromycin",
    brandNames: ["Zithromax", "Z-Pak"],
    commonSpokenVariants: ["azithromycin", "zithromax", "z pak", "zpack", "Z pack"],
    commonMisspellings: ["azythromycin"],
    drugClass: "Antibiotic",
    subclass: "Macrolide",
    route: "oral",
  },
  {
    genericName: "doxycycline",
    brandNames: ["Vibramycin", "Doryx", "Oracea"],
    commonSpokenVariants: ["doxycycline", "vibramycin", "doryx", "oracea", "doxy"],
    commonMisspellings: ["doxycylcine", "doxycicline"],
    drugClass: "Antibiotic",
    subclass: "Tetracycline",
    route: "oral",
    notes: "Common in acne/respiratory use",
  },
  {
    genericName: "nitrofurantoin",
    brandNames: ["Macrobid", "Macrodantin"],
    commonSpokenVariants: ["nitrofurantoin", "macrobid", "macrodantin", "UTI antibiotic"],
    commonMisspellings: ["nitrofurantion", "macrobidd"],
    drugClass: "Antibiotic",
    subclass: "Urinary anti-infective",
    route: "oral",
  },
  {
    genericName: "fluconazole",
    brandNames: ["Diflucan"],
    commonSpokenVariants: ["fluconazole", "diflucan", "yeast infection pill", "antifungal"],
    commonMisspellings: ["flucanazole", "diflucin"],
    drugClass: "Antifungal",
    subclass: "Azole antifungal",
    route: "oral",
  },
  {
    genericName: "valacyclovir",
    brandNames: ["Valtrex"],
    commonSpokenVariants: ["valacyclovir", "valtrex", "herpes antiviral", "cold sore medication"],
    commonMisspellings: ["valcyclovir", "valtrexx"],
    drugClass: "Antiviral",
    subclass: "Herpes antiviral",
    route: "oral",
  },

  // ─── Dermatology ─────────────────────────────────────────────────────────────
  {
    genericName: "tretinoin",
    brandNames: ["Retin-A", "Altreno", "Atralin"],
    commonSpokenVariants: ["tretinoin", "retin a", "retina", "altreno", "atralin", "retinoid cream", "vitamin A cream"],
    commonMisspellings: ["tretnoin", "retinay", "tretinoine"],
    drugClass: "Topical retinoid",
    subclass: "Vitamin A derivative",
    route: "topical",
    notes: "Differentiate from isotretinoin",
  },
  {
    genericName: "isotretinoin",
    brandNames: ["Absorica", "Claravis", "Amnesteem", "Accutane"],
    commonSpokenVariants: ["isotretinoin", "accutane", "absorica", "claravis", "amnesteem", "oral retinoid", "acne pill"],
    commonMisspellings: ["isotretenoin", "accutan"],
    drugClass: "Retinoid",
    subclass: "Oral retinoid",
    route: "oral",
  },
  {
    genericName: "clindamycin topical",
    brandNames: ["Cleocin T", "Clindagel"],
    commonSpokenVariants: ["clindamycin topical", "clindagel", "cleocin t", "clinda gel", "topical antibiotic"],
    commonMisspellings: ["clindamcyin topical", "clindagell"],
    drugClass: "Topical antibiotic",
    subclass: "Lincosamide",
    route: "topical",
    notes: "Keep separate from oral if possible",
  },
  {
    genericName: "minocycline",
    brandNames: ["Minocin", "Solodyn"],
    commonSpokenVariants: ["minocycline", "minocin", "solodyn", "acne antibiotic"],
    commonMisspellings: ["minocyclin", "solodin"],
    drugClass: "Antibiotic",
    subclass: "Tetracycline",
    route: "oral",
    notes: "Common in acne",
  },
  {
    genericName: "hydroquinone",
    brandNames: [],
    commonSpokenVariants: ["hydroquinone", "skin lightener", "dark spot cream", "depigmenting cream"],
    commonMisspellings: ["hydroquinon"],
    drugClass: "Dermatologic",
    subclass: "Depigmenting agent",
    route: "topical",
  },
  {
    genericName: "tretinoin-clindamycin",
    brandNames: [],
    commonSpokenVariants: ["tretinoin and clindamycin", "retinoid and clinda", "combination acne regimen"],
    commonMisspellings: ["tretinoin clindamcyin"],
    drugClass: "Dermatologic",
    subclass: "Combined acne regimen",
    route: "topical",
    notes: "Nonstandard shorthand entry for transcript interpretation",
  },
  {
    genericName: "minoxidil",
    brandNames: ["Rogaine", "Kirkland Minoxidil"],
    commonSpokenVariants: ["minoxidil", "rogaine", "hair regrowth", "topical hair medication", "minoxidil foam", "minoxidil solution"],
    commonMisspellings: ["minoxidol", "minoxidile", "monoxidil"],
    drugClass: "Dermatologic",
    subclass: "Hair Loss Treatment",
    route: "topical|oral",
  },
];

/**
 * Convert seed entries to MedicationEntry-compatible objects with virtual negative IDs.
 * Negative IDs ensure system entries never clash with DB-assigned positive IDs.
 */
export function getSeedAsEntries() {
  return SYSTEM_MEDICATIONS.map((s, idx): {
    id: number;
    dictionaryId: number;
    clinicianId: number | null;
    genericName: string;
    brandNames: string[];
    commonSpokenVariants: string[];
    commonMisspellings: string[];
    drugClass: string | null;
    subclass: string | null;
    route: string | null;
    notes: string | null;
    isSystem: true;
  } => ({
    id: -(idx + 1),
    dictionaryId: -1,
    clinicianId: null,
    genericName: s.genericName,
    brandNames: s.brandNames,
    commonSpokenVariants: s.commonSpokenVariants,
    commonMisspellings: s.commonMisspellings,
    drugClass: s.drugClass ?? null,
    subclass: s.subclass ?? null,
    route: s.route ?? null,
    notes: s.notes ?? null,
    isSystem: true,
  }));
}
